### ISSUE TITLE
请使用docker

### ISSUE THREAD

**Issue by neo1218** [hdgs/guisheng_be#8]
看你加了celery和redis, 环境有点复杂了。 开发的时候就可以用docker和docker-compose.
安装:  http://get.daocloud.io/
docker镜像加速器: https://www.daocloud.io/mirror.html#accelerator-doc

然后定义3个文件, 分别对应到3个环境(很清晰)

+ docker-compose.dev.yml -> 开发环境
+ docker-compose.txt.yml -> 测试环境
+ docker-compose.yml -> 部署环境

然后 xxx.env 文件定义环境变量, 这个文件放在本地.
开发的时候flask app跑本地, 连接docker容器公有端口.
测试、部署的时候把app打包到容器里就行了.

可以参考华师匣子

![screen shot 2016-12-11 at 23 52 53](https://cloud.githubusercontent.com/assets/10671733/21081241/2a212094-bffd-11e6-943c-33c005e325b0.png)
![screen shot 2016-12-11 at 23 53 12](https://cloud.githubusercontent.com/assets/10671733/21081242/3dab470c-bffd-11e6-9d29-ed65e27d746c.png)
![screen shot 2016-12-11 at 23 53 36](https://cloud.githubusercontent.com/assets/10671733/21081247/4477f440-bffd-11e6-8337-ac0214f860f4.png)

**Comment by zxc0328** [comment]
不是建议啦 是团队的规范 做一个项目接触了很多 就是一个不断尝试新事物的过程
